# -*-coding:utf-8-*-

# coder: Jiawen Zhu
# date: 2019.6.9
# state: half modified

# devices
gpu_device: '0'

# net architecture
architecture: simple_model

# datasets
num_classes: 10
train_data_num: 50000
dataset: captcha
data_path: ./datasets/captcha_images/images/train/
val_data_path: ./datasets/captcha_images/images/val/
record_train_data_path: ./datasets/captcha_images/tfrecord/train.record
input_size_w: 32
input_size_h: 32
input_resize_w: 32
input_resize_h: 32
# depth
input_size_d: 3

# training parameters
train_steps: 2000
batch_size: 128
# val
val_batch: 128

# learning rate scheduler
lr_scheduler:
  init_lr: 0.01

# optimizer
optimize:
  momentum: 0.9

# output
save_pb_direct: False
ckpt_path: ./exp_output/captcha_simple_model/ckpt/
pb_direct_path: ./exp_output/captcha_simple_model/pb_saved_direct/

